services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: libsys
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
